# Baseic base conversion tool config file

# Set output converters to be executed when none are specified
# Allowed values: "DEC", "BIN", "HEX", "OCT", "ASCII"
# default_outconvs = ["DEC", "BIN", "HEX", "OCT", "ASCII"]

# Set input converters to be executed when not specified
# Allowed values: "DEC", "BIN", "HEX", "OCT", "ASCII"
# default_inconvs = ["DEC", "BIN", "HEX", "OCT", "ASCII"]
