# Baseic base conversion tool config file

# Set output converters to be executed when none are specified
# Allowed values: "DEC", "BIN", "HEX"
# default_outconvs = ["DEC", "BIN", "HEX"]

# Set input converters to be executed when not specified
# Allowed values: "DEC", "BIN", "HEX"
# default_inconvs = ["DEC", "BIN", "HEX"]
